### ISSUE TITLE
LimeSDR and RTL-SDR compatibility

### ISSUE THREAD

**Issue by minkione** [SignalsEverywhere/gr-dect2#2]
Quick question, I guess should be fairly easy to adapt it to be used with RTL-SDR and LimeSDR.
Could you point at which files I should look into, to make it compatible?
Thanks in advance for the hint. :smiley:

**Comment by KR0SIV** [comment]
Sure, this should be pretty doable. I should grab my limeSDR and test it myself some time.

For the RTL-SDR You actually need the E4000 tuner as the R820T doesn't support that US DECT range.
To do this with the LimeSDR You'll need to ensure those blocks are installed.

https://wiki.myriadrf.org/Gr-limesdr_Plugin_for_GNURadio

The above will get the LimeSDR block installed and you'd replace the existing Osmocom HackRF block with it.

Below is how you'd set this up for an RTL-SDR

![image](https://user-images.githubusercontent.com/13837655/50227484-d3243a80-0373-11e9-9fd4-6f5654438738.png)

Taking a look at this link will show you all the osmocom source variables, It's the exact block just I've set mine to hackrf=0

https://osmocom.org/projects/gr-osmosdr/wiki
