### ISSUE TITLE
ImportError: No module named dect2

### ISSUE THREAD

**Issue by redrob** [SignalsEverywhere/gr-dect2#4]
I seem to be getting this error in OSX 10.13.6. GRC is installed via MacPorts. Using Python 2.7. Not sure if this is a path issue or what? 

$ gnuradio-companion dect2_Hackrf.grc
<<< Welcome to GNU Radio Companion 3.7.13.4 >>>

Block paths:
	/Users/ga/.grc_gnuradio
	/opt/local/share/gnuradio/grc/blocks

Loading: "/Users/ga/gnuradio/gr-dect2/grc/dect2_Hackrf.grc"
>>> Done

Generating: '/Users/ga/gnuradio/gr-dect2/grc/top_block.py'

Executing: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u /Users/ga/gnuradio/gr-dect2/grc/top_block.py

Traceback (most recent call last):
  File "/Users/ga/gnuradio/gr-dect2/grc/top_block.py", line 31, in <module>
    import dect2
ImportError: No module named dect2

**Comment by giomf** [comment]
This is because this package was installed to /usr/local/lib64/python2.7/site-packages/
Check if this path is listed under "python -m site"

If not, python is not able to load this package and you have to add it manually.
