### ISSUE TITLE
I only hear noise

### ISSUE THREAD

**Issue by enrutador** [SignalsEverywhere/gr-dect2#5]
good afternoon
Thanks for the implementation in hackrf. I have a doubt :

  In the gnu scheme the g721 decoder block is shown, is it necessary to have the binary "/ usr / local / src / g72x / decode-g72x" in some expecial way? . I only hear noise.

Could it be the decoder or the encryption?
Thank you

**Comment by KR0SIV** [comment]
It could be your processing power, are you in a virtual machine or using a low power pc?
